import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { Client } from "pg";
import { readFileSync } from "node:fs";
import { validatePackage } from "../../src/curriculum/validation";

const url=process.env.TEST_DATABASE_URL;
const run=url?describe:describe.skip;
const ids={org:"10000000-0000-0000-0000-000000000001",admin:"10000000-0000-0000-0000-000000000002",learner:"10000000-0000-0000-0000-000000000003",other:"10000000-0000-0000-0000-000000000004",orgB:"10000000-0000-0000-0000-000000000005",adminB:"10000000-0000-0000-0000-000000000006"};
let db:Client;

async function asUser(userId:string,sql:string,params:unknown[]=[]){await db.query("begin");try{await db.query("set local role authenticated");await db.query("select set_config('request.jwt.claim.sub',$1,true)",[userId]);const result=await db.query(sql,params);await db.query("commit");return result;}catch(error){await db.query("rollback");throw error;}}

run("Iteration 1 PostgreSQL certification",()=>{
  beforeAll(async()=>{db=new Client({connectionString:url});await db.connect();await db.query("insert into auth.users(id,email) values($1,'admin@local.test'),($2,'learner@local.test'),($3,'other@local.test'),($4,'admin-b@local.test') on conflict(id) do nothing",[ids.admin,ids.learner,ids.other,ids.adminB]);await db.query("insert into public.organizations(id,stable_id,name) values($1,'cert-org','Certification Org'),($2,'other-org','Other Org') on conflict(id) do nothing",[ids.org,ids.orgB]);await db.query("insert into public.organization_memberships(organization_id,user_id,role) values($1,$2,'administrator'),($1,$3,'learner'),($4,$5,'administrator') on conflict do nothing",[ids.org,ids.admin,ids.learner,ids.orgB,ids.adminB]);});
  afterAll(async()=>{await db?.end();});

  it("enforces tenant membership and permits an organization member",async()=>{expect((await asUser(ids.learner,"select stable_id from public.organizations")).rows).toEqual([{stable_id:"cert-org"}]);expect((await asUser(ids.other,"select stable_id from public.organizations")).rowCount).toBe(0);});
  it("denies an unauthorized import",async()=>{await expect(asUser(ids.learner,"select public.execute_curriculum_import($1,$2,$3,$4,false)",[ids.org,"denied",{},"digest"])).rejects.toThrow(/forbidden|permission denied/i);});
  it("denies cross-tenant writes even to an administrator",async()=>{await expect(asUser(ids.admin,"insert into public.curriculum_authorities(organization_id,stable_id,name,country_code) values($1,'forged','Forged','US')",[ids.orgB])).rejects.toThrow(/row-level security|permission denied/i);});
  it("denies cross-tenant update and delete",async()=>{await db.query("insert into public.curriculum_authorities(organization_id,stable_id,name,country_code) values($1,'org-b-authority','Org B','US') on conflict do nothing",[ids.orgB]);expect((await asUser(ids.admin,"update public.curriculum_authorities set name='Compromised' where organization_id=$1",[ids.orgB])).rowCount).toBe(0);expect((await asUser(ids.admin,"delete from public.curriculum_authorities where organization_id=$1",[ids.orgB])).rowCount).toBe(0);});
  it("rolls back an invalid import transaction",async()=>{await expect(asUser(ids.admin,"select public.execute_curriculum_import($1,$2,$3,$4,false)",[ids.org,"invalid",{package:{stableId:"broken"},nodes:[],relationships:[]},"digest"])).rejects.toThrow();const result=await db.query("select count(*)::int count from public.import_runs where idempotency_key='invalid'");expect(result.rows[0].count).toBe(0);});
  it("contains required constraints, indexes, and RLS",async()=>{const rls=await db.query("select count(*)::int count from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relrowsecurity");expect(rls.rows[0].count).toBeGreaterThanOrEqual(15);const indexes=await db.query("select count(*)::int count from pg_indexes where schemaname='public' and indexname in ('curriculum_nodes_browse_idx','package_versions_resolution_idx','audit_events_aggregate_idx')");expect(indexes.rows[0].count).toBe(3);});
  it("commits an import, creates audit evidence, and replays idempotently",async()=>{const document=JSON.parse(readFileSync(new URL("../../fixtures/curriculum/interoperability-fixture.json",import.meta.url),"utf8"));const plan=validatePackage(document);expect(plan.valid).toBe(true);const first=await asUser(ids.admin,"select public.execute_curriculum_import($1,$2,$3,$4,false) result",[ids.org,"interop-import",document,plan.digest]);const replay=await asUser(ids.admin,"select public.execute_curriculum_import($1,$2,$3,$4,false) result",[ids.org,"interop-import",document,plan.digest]);expect(first.rows[0].result.replayed).toBe(false);expect(replay.rows[0].result.replayed).toBe(true);const counts=await db.query("select (select count(*)::int from public.curriculum_package_versions where organization_id=$1) versions,(select count(*)::int from public.audit_events where organization_id=$1 and event_type='curriculum.imported') audits",[ids.org]);expect(counts.rows[0]).toEqual({versions:1,audits:1});});
  it("rejects idempotency-key payload conflicts",async()=>{await expect(asUser(ids.admin,"select public.execute_curriculum_import($1,$2,$3,$4,false)",[ids.org,"interop-import",{},"different-digest"])).rejects.toThrow(/idempotency key reused/i);});
});
