import{afterAll,beforeAll,describe,expect,it}from"vitest";
import{Client}from"pg";
const url=process.env.TEST_DATABASE_URL,run=url?describe:describe.skip;
const ids={org:"10000000-0000-0000-0000-000000000001",learner:"10000000-0000-0000-0000-000000000003",other:"10000000-0000-0000-0000-000000000004",adminB:"10000000-0000-0000-0000-000000000006",teacher:"10000000-0000-0000-0000-000000000007",guardian:"10000000-0000-0000-0000-000000000008"};
let db:Client;
async function asUser(user:string,sql:string,params:unknown[]=[]){await db.query("begin");try{await db.query("set local role authenticated");await db.query("select set_config('request.jwt.claim.sub',$1,true)",[user]);const r=await db.query(sql,params);await db.query("commit");return r;}catch(e){await db.query("rollback");throw e;}}
async function isolated(user:string,sql:string,params:unknown[]=[]){const c=new Client({connectionString:url});await c.connect();try{await c.query("begin");await c.query("set local role authenticated");await c.query("select set_config('request.jwt.claim.sub',$1,true)",[user]);const r=await c.query(sql,params);await c.query("commit");return r;}catch(e){await c.query("rollback");throw e;}finally{await c.end();}}
run("Iteration 2 adversarial security and concurrency",()=>{
 beforeAll(async()=>{db=new Client({connectionString:url});await db.connect();});afterAll(async()=>{await db.end();});
 it("enforces direct RLS reads without protected-shape leakage",async()=>{for(const table of["classes","class_enrollments","assignments","learning_sessions","assessment_attempts","assessment_scores","mastery_decisions","mastery_overrides","learning_recommendations","remediation_assignments","intervention_notes","audit_events"]){expect((await asUser(ids.other,`select * from public.${table}`)).rowCount,table).toBe(0);}expect((await asUser(ids.adminB,"select id from public.assignments where organization_id=$1",[ids.org])).rowCount).toBe(0);expect((await asUser(ids.other,"select id from public.rubric_versions")).rowCount).toBe(0);await expect(asUser(ids.other,"select*from public.learning_outbox")).rejects.toThrow(/permission denied/i);await expect(asUser(ids.learner,"select answer_key from public.assessment_items")).rejects.toThrow(/permission denied/i);});
 it("denies mutation, withdrawn enrollment, expired windows, and oversized payloads",async()=>{const a=(await db.query("select id,class_id,lesson_version_id,assessment_version_id from public.assignments where organization_id=$1 limit 1",[ids.org])).rows[0];expect((await asUser(ids.learner,"update public.assignments set created_by=$1 where id=$2",[ids.learner,a.id])).rowCount).toBe(0);const expired=(await db.query("insert into public.assignments(organization_id,class_id,lesson_version_id,assessment_version_id,state,due_at,created_by)values($1,$2,$3,$4,'active',now()-interval '1 hour',$5)returning id",[ids.org,a.class_id,a.lesson_version_id,a.assessment_version_id,ids.teacher])).rows[0].id;await expect(asUser(ids.learner,"select*from public.start_learning_session($1,'expired-start')",[expired])).rejects.toThrow(/unavailable/i);await expect(asUser(ids.learner,"select public.submit_assessment($1,'expired-submit','[]')",[expired])).rejects.toThrow(/unavailable/i);await db.query("update public.class_enrollments set status='withdrawn'where class_id=$1 and learner_id=$2",[a.class_id,ids.learner]);await expect(asUser(ids.learner,"select*from public.start_learning_session($1,'withdrawn-start')",[a.id])).rejects.toThrow(/forbidden/i);await db.query("update public.class_enrollments set status='active'where class_id=$1 and learner_id=$2",[a.class_id,ids.learner]);});
 it("revokes guardian access and isolates internal notes",async()=>{await db.query("insert into public.intervention_notes(organization_id,learner_id,objective_id,teacher_id,note,guardian_visible)select $1,$2,id,$3,'Internal only',false from public.curriculum_nodes where organization_id=$1 limit 1",[ids.org,ids.learner,ids.teacher]);expect((await asUser(ids.guardian,"select note from public.intervention_notes")).rowCount).toBe(0);await db.query("update public.guardian_relationships set status='revoked'where organization_id=$1 and guardian_id=$2 and learner_id=$3",[ids.org,ids.guardian,ids.learner]);expect((await asUser(ids.guardian,"select id from public.mastery_decisions")).rowCount).toBe(0);expect((await asUser(ids.guardian,"select id from public.remediation_assignments")).rowCount).toBe(0);await db.query("update public.guardian_relationships set status='active'where organization_id=$1 and guardian_id=$2 and learner_id=$3",[ids.org,ids.guardian,ids.learner]);});
 it("converges concurrent session creation and rejects oversized domain payloads",async()=>{const b=(await db.query("select class_id,lesson_version_id,assessment_version_id from public.assignments where organization_id=$1 limit 1",[ids.org])).rows[0];const fresh=(await db.query("insert into public.assignments(organization_id,class_id,lesson_version_id,assessment_version_id,state,created_by)values($1,$2,$3,$4,'active',$5)returning id",[ids.org,b.class_id,b.lesson_version_id,b.assessment_version_id,ids.teacher])).rows[0].id;const r=await Promise.all([isolated(ids.learner,"select id from public.start_learning_session($1,'concurrent-a')",[fresh]),isolated(ids.learner,"select id from public.start_learning_session($1,'concurrent-b')",[fresh])]);expect(r[0].rows[0].id).toBe(r[1].rows[0].id);expect((await db.query("select count(*)::int n from public.learning_sessions where assignment_id=$1 and learner_id=$2",[fresh,ids.learner])).rows[0].n).toBe(1);await expect(asUser(ids.learner,"select public.submit_assessment($1,'oversized',$2)",[fresh,JSON.stringify(Array.from({length:201},()=>({})))])).rejects.toThrow(/invalid response payload/i);});
});
