begin;
alter table public.learning_recommendations drop constraint learning_recommendations_status_check;
alter table public.learning_recommendations add constraint learning_recommendations_status_check check(status in('available','accepted','dismissed','completed','replaced','continued','resolved','no_content'));
create table public.remediation_assignments(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),recommendation_id uuid not null references public.learning_recommendations(id),learner_id uuid not null references auth.users(id),objective_id uuid not null references public.curriculum_nodes(id),lesson_version_id uuid not null references public.lesson_versions(id),reassessment_assignment_id uuid references public.assignments(id),assigned_by uuid not null references auth.users(id),status text not null check(status in('assigned','in_progress','paused','completed','reassessment_started','resolved','continued','replaced')),progress jsonb not null default'{}',lock_version integer not null default 0,idempotency_key text not null,available_from timestamptz,due_at timestamptz,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,idempotency_key)
);
create index remediation_learner_status_idx on public.remediation_assignments(learner_id,status,updated_at desc);
create index remediation_recommendation_idx on public.remediation_assignments(recommendation_id,created_at desc);
alter table public.remediation_assignments enable row level security;
create policy remediation_authorized_read on public.remediation_assignments for select using(learner_id=auth.uid()or public.has_guardian_access(organization_id,learner_id)or public.has_org_role(organization_id,array['educator','administrator','platform_administrator']::public.app_role[]));
grant select on public.remediation_assignments to authenticated;

create function public.assign_remediation(p_recommendation uuid,p_lesson_version uuid,p_reassessment_assignment uuid,p_idempotency text,p_available_from timestamptz default null,p_due_at timestamptz default null)returns public.remediation_assignments language plpgsql security definer set search_path=''as $$
declare r public.learning_recommendations;l public.lesson_versions;a public.assignments;c public.classes;result public.remediation_assignments;
begin select*into r from public.learning_recommendations where id=p_recommendation for update;if r.id is null or r.kind<>'remediation'then raise exception'remediation recommendation required';end if;select*into l from public.lesson_versions where id=p_lesson_version and organization_id=r.organization_id and objective_id=r.objective_id and state='published';if l.id is null then raise exception'eligible remediation content required';end if;select x.*into a from public.assignments x where x.id=p_reassessment_assignment and x.organization_id=r.organization_id;select*into c from public.classes where id=a.class_id;if a.id is null or c.teacher_id<>auth.uid()then raise exception'forbidden'using errcode='42501';end if;if not exists(select 1 from public.class_enrollments e where e.class_id=a.class_id and e.learner_id=r.learner_id and e.status='active')then raise exception'learner is not actively enrolled';end if;
insert into public.remediation_assignments(organization_id,recommendation_id,learner_id,objective_id,lesson_version_id,reassessment_assignment_id,assigned_by,status,idempotency_key,available_from,due_at)values(r.organization_id,r.id,r.learner_id,r.objective_id,l.id,a.id,auth.uid(),'assigned',p_idempotency,p_available_from,p_due_at)on conflict(organization_id,idempotency_key)do update set idempotency_key=excluded.idempotency_key returning*into result;update public.learning_recommendations set status='accepted'where id=r.id;insert into public.recommendation_events(organization_id,recommendation_id,actor_id,from_status,to_status,reason,replacement_lesson_version_id,reassessment_assignment_id,idempotency_key)values(r.organization_id,r.id,auth.uid(),r.status,'accepted','Remediation assigned',l.id,a.id,'event:'||p_idempotency)on conflict(organization_id,idempotency_key)do nothing;insert into public.learning_outbox(organization_id,event_key,event_type,payload)values(r.organization_id,'outbox:'||p_idempotency,'remediation.assigned',jsonb_build_object('remediationId',result.id))on conflict(event_key)do nothing;insert into public.audit_events(organization_id,actor_id,event_type,aggregate_type,aggregate_id)values(r.organization_id,auth.uid(),'remediation.assigned','remediation_assignment',result.id);return result;end$$;

create function public.save_remediation_progress(p_remediation uuid,p_expected_lock integer,p_progress jsonb,p_state text,p_idempotency text)returns public.remediation_assignments language plpgsql security definer set search_path=''as $$
declare r public.remediation_assignments;result public.remediation_assignments;begin select*into r from public.remediation_assignments where id=p_remediation for update;if r.id is null or r.learner_id<>auth.uid()then raise exception'forbidden'using errcode='42501';end if;if(r.available_from is not null and r.available_from>now())or(r.due_at is not null and r.due_at<now())then raise exception'remediation unavailable';end if;if p_state not in('in_progress','paused','completed')then raise exception'invalid remediation state';end if;if r.lock_version<>p_expected_lock then raise exception'stale remediation version'using errcode='40001';end if;update public.remediation_assignments set progress=p_progress,status=p_state,lock_version=lock_version+1,started_at=coalesce(started_at,now()),completed_at=case when p_state='completed'then coalesce(completed_at,now())else completed_at end,updated_at=now()where id=r.id returning*into result;insert into public.learning_outbox(organization_id,event_key,event_type,payload)values(r.organization_id,p_idempotency,'remediation.progress_saved',jsonb_build_object('remediationId',r.id,'state',p_state,'lockVersion',result.lock_version))on conflict(event_key)do nothing;return result;end$$;

create function public.start_remediation_reassessment(p_remediation uuid,p_idempotency text)returns public.assessment_attempts language plpgsql security definer set search_path=''as $$
declare r public.remediation_assignments;a public.assignments;result public.assessment_attempts;begin select*into r from public.remediation_assignments where id=p_remediation for update;if r.id is null or r.learner_id<>auth.uid()then raise exception'forbidden'using errcode='42501';end if;if r.status<>'completed'then raise exception'remediation completion required';end if;select*into a from public.assignments where id=r.reassessment_assignment_id and state='active'and(available_from is null or available_from<=now())and(due_at is null or due_at>=now());if a.id is null then raise exception'reassessment unavailable';end if;if(select count(*)from public.assessment_attempts x where x.assignment_id=a.id and x.learner_id=auth.uid())>=a.attempt_limit then raise exception'attempt limit reached';end if;insert into public.assessment_attempts(organization_id,assignment_id,learner_id,assessment_version_id,state,idempotency_key)values(a.organization_id,a.id,auth.uid(),a.assessment_version_id,'created',p_idempotency)on conflict(organization_id,idempotency_key)do update set idempotency_key=excluded.idempotency_key returning*into result;update public.remediation_assignments set status='reassessment_started',updated_at=now()where id=r.id;insert into public.learning_outbox(organization_id,event_key,event_type,payload)values(r.organization_id,'outbox:'||p_idempotency,'reassessment.started',jsonb_build_object('remediationId',r.id,'attemptId',result.id))on conflict(event_key)do nothing;return result;end$$;

create function public.resolve_remediation(p_remediation uuid,p_attempt uuid,p_idempotency text)returns public.remediation_assignments language plpgsql security definer set search_path=''as $$
declare r public.remediation_assignments;a public.assessment_attempts;c public.classes;result public.remediation_assignments;outcome text;begin select*into r from public.remediation_assignments where id=p_remediation for update;select*into a from public.assessment_attempts where id=p_attempt;select cl.*into c from public.assignments n join public.classes cl on cl.id=n.class_id where n.id=a.assignment_id;if r.id is null or a.id is null or a.learner_id<>r.learner_id or a.assignment_id<>r.reassessment_assignment_id or a.state<>'scored'then raise exception'authoritative reassessment score required';end if;if c.teacher_id<>auth.uid()and not public.has_org_role(r.organization_id,array['administrator','platform_administrator']::public.app_role[])then raise exception'forbidden'using errcode='42501';end if;outcome=case when exists(select 1 from public.mastery_decisions d where d.attempt_id=a.id and d.new_state in('proficient','advanced'))then'resolved'else'continued'end;update public.remediation_assignments set status=outcome,updated_at=now()where id=r.id returning*into result;update public.learning_recommendations set status=outcome where id=r.recommendation_id;insert into public.recommendation_events(organization_id,recommendation_id,actor_id,from_status,to_status,reason,reassessment_assignment_id,idempotency_key)values(r.organization_id,r.recommendation_id,auth.uid(),'accepted',outcome,'Authoritative reassessment reviewed',r.reassessment_assignment_id,p_idempotency)on conflict(organization_id,idempotency_key)do nothing;insert into public.learning_outbox(organization_id,event_key,event_type,payload)values(r.organization_id,'outbox:'||p_idempotency,'remediation.'||outcome,jsonb_build_object('remediationId',r.id,'attemptId',a.id))on conflict(event_key)do nothing;return result;end$$;

create function public.submit_remediation_reassessment(p_remediation uuid,p_attempt uuid,p_responses jsonb,p_idempotency text)returns jsonb language plpgsql security definer set search_path=''as $$
declare r public.remediation_assignments;a public.assessment_attempts;earned numeric:=0;possible numeric:=0;outcomes jsonb;next_state public.mastery_state;ratio numeric;begin select*into r from public.remediation_assignments where id=p_remediation for update;select*into a from public.assessment_attempts where id=p_attempt for update;if r.id is null or r.learner_id<>auth.uid()or a.learner_id<>auth.uid()or a.assignment_id<>r.reassessment_assignment_id then raise exception'forbidden'using errcode='42501';end if;if a.state='scored'then return jsonb_build_object('attemptId',a.id,'replayed',true);end if;if a.state<>'created'then raise exception'attempt not submittable';end if;with scored as(select i.id,i.points,case when x.value->>'option'=i.answer_key->>'correctOption'then i.points else 0 end got from public.assessment_items i left join lateral(select value from jsonb_array_elements(p_responses)where value->>'itemId'=i.id::text limit 1)x on true where i.assessment_version_id=a.assessment_version_id),agg as(select coalesce(sum(got),0)e,coalesce(sum(points),0)p,jsonb_agg(jsonb_build_object('itemId',id,'earned',got,'possible',points))o from scored)select e,p,o into earned,possible,outcomes from agg;update public.assessment_attempts set state='scored',responses=p_responses,submitted_at=now(),finalized_at=now()where id=a.id;insert into public.assessment_scores(organization_id,attempt_id,scoring_version,earned,possible,outcomes)values(a.organization_id,a.id,'reassessment-1.0',earned,possible,outcomes)on conflict(attempt_id,scoring_version)do nothing;ratio=case when possible=0 then 0 else earned/possible end;next_state=case when ratio>=.9 then'advanced'::public.mastery_state when ratio>=.75 then'proficient'::public.mastery_state when ratio>=.5 then'developing'::public.mastery_state else'emerging'::public.mastery_state end;insert into public.mastery_decisions(organization_id,learner_id,objective_id,attempt_id,previous_state,new_state,ratio,policy_version,evidence,explanation)values(a.organization_id,a.learner_id,r.objective_id,a.id,'not_assessed',next_state,ratio,'reassessment-1.0',jsonb_build_object('score',earned,'possible',possible),earned||' of '||possible||' reassessment points')on conflict(attempt_id,policy_version)do nothing;insert into public.learning_outbox(organization_id,event_key,event_type,payload)values(r.organization_id,'outbox:'||p_idempotency,'reassessment.scored',jsonb_build_object('attemptId',a.id,'mastery',next_state))on conflict(event_key)do nothing;return jsonb_build_object('attemptId',a.id,'earned',earned,'possible',possible,'mastery',next_state,'replayed',false);end$$;

create function public.mark_recommendation_no_content(p_recommendation uuid,p_reason text,p_idempotency text)returns public.learning_recommendations language plpgsql security definer set search_path=''as $$
declare r public.learning_recommendations;a public.assessment_attempts;c public.classes;result public.learning_recommendations;begin if length(trim(p_reason))=0 then raise exception'actionable reason required';end if;select*into r from public.learning_recommendations where id=p_recommendation for update;select at.*into a from public.mastery_decisions d join public.assessment_attempts at on at.id=d.attempt_id where d.id=r.mastery_decision_id;select cl.*into c from public.assignments n join public.classes cl on cl.id=n.class_id where n.id=a.assignment_id;if c.teacher_id<>auth.uid()then raise exception'forbidden'using errcode='42501';end if;update public.learning_recommendations set status='no_content'where id=r.id returning*into result;insert into public.recommendation_events(organization_id,recommendation_id,actor_id,from_status,to_status,reason,idempotency_key)values(r.organization_id,r.id,auth.uid(),r.status,'no_content',p_reason,p_idempotency)on conflict(organization_id,idempotency_key)do nothing;return result;end$$;

grant execute on function public.assign_remediation(uuid,uuid,uuid,text,timestamptz,timestamptz),public.save_remediation_progress(uuid,integer,jsonb,text,text),public.start_remediation_reassessment(uuid,text),public.submit_remediation_reassessment(uuid,uuid,jsonb,text),public.resolve_remediation(uuid,uuid,text),public.mark_recommendation_no_content(uuid,text,text)to authenticated;
commit;
